# -*- coding: utf-8 -*-
"""Phase_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fL13roSggtwHvsVM8QOvSDdBR3fijmX0

'''
Alex Agent — Phase 2: Memory System

Now with:
- Short-term memory (conversation history)
- Long-term memory (learning from past goals)
- Context awareness
- Multi-turn conversations
'''
"""

!pip install -q google-genai

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Any

import google.genai as genai
from google.genai import types

from google.colab import userdata

GEMINI_API_KEY = userdata.get("GOOGLE_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError("GOOGLE_API_KEY not found in Colab Secrets")

client = genai.Client(api_key=GEMINI_API_KEY)

MODEL_NAME = "gemini-3.8-flash"

print("✅ Gemini client initialized")
print(f"🤖 Model: {MODEL_NAME}")

@dataclass
class MemoryEntry:
    key: str
    value: Any
    memory_type: str
    importance: float = 0.5
    timestamp: str = field(
        default_factory=lambda: datetime.now().isoformat()
    )

    def to_dict(self):
        return {
            "key": self.key,
            "value": self.value,
            "memory_type": self.memory_type,
            "importance": self.importance,
            "timestamp": self.timestamp
        }

@dataclass
class ConversationTurn:
    turn_id: int
    user_message: str
    assistant_response: str
    timestamp: str = field(
        default_factory=lambda: datetime.now().isoformat()
    )

    def to_dict(self):
        return {
            "turn_id": self.turn_id,
            "user_message": self.user_message,
            "assistant_response": self.assistant_response,
            "timestamp": self.timestamp
        }

@dataclass
class ConversationTurn:
    turn_id: int
    user_message: str
    assistant_response: str
    timestamp: str = field(
        default_factory=lambda: datetime.now().isoformat()
    )

    def to_dict(self):
        return {
            "turn_id": self.turn_id,
            "user_message": self.user_message,
            "assistant_response": self.assistant_response,
            "timestamp": self.timestamp
        }

class ShortTermMemory:

    def __init__(self, max_entries: int = 10):
        self.max_entries = max_entries
        self.entries: List[MemoryEntry] = []
        self.conversation_turns: List[ConversationTurn] = []

    def add_entry(self, entry: MemoryEntry):
        self.entries.append(entry)

        if len(self.entries) > self.max_entries:
            self.entries.pop(0)

    def add_conversation(
        self,
        user_message: str,
        assistant_response: str
    ):
        turn = ConversationTurn(
            turn_id=len(self.conversation_turns),
            user_message=user_message,
            assistant_response=assistant_response
        )

        self.conversation_turns.append(turn)

        if len(self.conversation_turns) > self.max_entries:
            self.conversation_turns.pop(0)

    def get_recent_entries(self):
        return [
            entry.to_dict()
            for entry in self.entries
        ]

    def get_recent_conversations(self):
        return [
            turn.to_dict()
            for turn in self.conversation_turns
        ]

    def clear(self):
        self.entries.clear()
        self.conversation_turns.clear()

class LongTermMemory:

    def __init__(self):
        self.memories: Dict[str, MemoryEntry] = {}

        self.goal_patterns: Dict[str, int] = {}

        self.user_preferences: Dict[str, Any] = {}

    def save(self, entry: MemoryEntry):

        self.memories[entry.key] = entry

    def get(self, key: str):

        entry = self.memories.get(key)

        if entry:
            return entry.value

        return None

    def get_all(self):

        return {
            key: value.to_dict()
            for key, value in self.memories.items()
        }

    def save_preference(self, key: str, value: Any):

        self.user_preferences[key] = value

    def record_goal_type(self, goal_type: str):

        self.goal_patterns[goal_type] = (
            self.goal_patterns.get(goal_type, 0) + 1
        )

class AgentMemory:

    def __init__(self):

        self.short_term = ShortTermMemory(
            max_entries=10
        )

        self.long_term = LongTermMemory()

    def remember(
        self,
        key: str,
        value: Any,
        memory_type: str = "general",
        importance: float = 0.5
    ):

        entry = MemoryEntry(
            key=key,
            value=value,
            memory_type=memory_type,
            importance=importance
        )

        self.long_term.save(entry)

    def remember_conversation(
        self,
        user_message: str,
        assistant_response: str
    ):

        self.short_term.add_conversation(
            user_message,
            assistant_response
        )

    def remember_goal(
        self,
        goal: str,
        goal_type: str,
        result: Dict
    ):

        self.remember(
            key=f"goal_{uuid.uuid4().hex[:8]}",
            value={
                "goal": goal,
                "goal_type": goal_type,
                "completed": result.get("completed", 0)
            },
            memory_type="goal",
            importance=0.8
        )

        self.long_term.record_goal_type(goal_type)

    def get_context(self, new_goal: str = ""):

        return {
            "recent_memory": self.short_term.get_recent_entries(),

            "recent_conversations":
                self.short_term.get_recent_conversations(),

            "long_term_memory":
                self.long_term.get_all(),

            "goal_patterns":
                self.long_term.goal_patterns,

            "user_preferences":
                self.long_term.user_preferences
        }

    def clear_short_term(self):

        self.short_term.clear()

class AlexAgent:

    def __init__(
        self,
        api_key: str,
        model: str = MODEL_NAME
    ):
        self.client = genai.Client(api_key=api_key)
        self.model = model

        self.tools_registry = {}
        self.execution_history = []

        print("✅ Alex Agent initialized")

    def register_tool(
        self,
        name: str,
        func,
        description: str
    ):
        self.tools_registry[name] = {
            "func": func,
            "description": description,
            "name": name
        }

        print(f"📍 Tool registered: {name}")

    def _call_gemini(self, prompt: str) -> str:

        try:

            interaction = self.client.interactions.create(
                model=self.model,
                input=prompt,
                generation_config={
                    "thinking_level": "low"
                }
            )

            return interaction.output_text

        except Exception as e:

            error_message = str(e)

            if "429" in error_message or "Rate limit" in error_message:

                return """
    {
        "error": "rate_limit",
        "message": "Gemini API rate limit exceeded."
    }
    """

            raise

    def understand_goal(
        self,
        user_goal: str
    ) -> Dict:

        prompt = f"""
You are Alex, an AI agent.

Understand the user's goal.

User goal:
"{user_goal}"

Return ONLY valid JSON:

{{
    "goal_type": "research | analysis | explanation | other",
    "complexity": "simple | medium | complex",
    "requires_tools": true,
    "analysis": "short explanation of what the user needs"
}}
"""

        response = self._call_gemini(prompt)

        try:
            return json.loads(response)

        except json.JSONDecodeError:

            return {
                "goal_type": "other",
                "complexity": "medium",
                "requires_tools": True,
                "analysis": response
            }

    def create_plan(
        self,
        user_goal: str,
        analysis: Dict
    ) -> List[Dict]:

        tools_desc = "\n".join(
            [
                f"- {name}: {tool['description']}"
                for name, tool in self.tools_registry.items()
            ]
        )

        memory_context = analysis.get(
            "memory_context",
            {}
        )

        prompt = f"""
You are Alex, an AI planning agent.

Create a plan to solve the user's goal.

USER GOAL:
{user_goal}

ANALYSIS:
{analysis.get("analysis", "")}

GOAL TYPE:
{analysis.get("goal_type", "other")}

PREVIOUS MEMORY:
{json.dumps(memory_context, indent=2)}

AVAILABLE TOOLS:
{tools_desc}

IMPORTANT:
- Use previous memory when it is relevant.
- Do not use a tool if it is unnecessary.
- Tool arguments must match the tool's expected parameters.
- If a tool is needed, provide the correct argument names.

Return ONLY valid JSON.

Format:

[
    {{
        "step": 1,
        "description": "what to do",
        "tool_required": true,
        "tool_name": "research",
        "args": {{
            "topic": "..."
        }}
    }}
]
"""

        response = self._call_gemini(prompt)

        try:

            plan = json.loads(response)

            if isinstance(plan, dict):
                plan = plan.get("steps", [])

            return plan

        except json.JSONDecodeError:

            return [
                {
                    "step": 1,
                    "description": "Reason about the user's request",
                    "tool_required": False,
                    "tool_name": None,
                    "args": {}
                }
            ]

    def execute_plan(
        self,
        plan: List[Dict]
    ) -> List[Dict]:

        results = []

        print("⚙️ Executing...")

        for step in plan:

            step_number = step.get(
                "step",
                len(results) + 1
            )

            description = step.get(
                "description",
                ""
            )

            print(
                f"\n   {step_number}. {description}"
            )

            try:

                if step.get("tool_required"):

                    tool_name = step.get(
                        "tool_name"
                    )

                    args = step.get(
                        "args",
                        {}
                    )

                    result = self._execute_tool(
                        tool_name,
                        args
                    )

                    print("      ✅")

                    results.append({
                        "step": step_number,
                        "description": description,
                        "tool": tool_name,
                        "args": args,
                        "result": result,
                        "success": True
                    })

                else:

                    result = self._execute_reasoning(
                        description
                    )

                    print("      ✅")

                    results.append({
                        "step": step_number,
                        "description": description,
                        "tool": "reasoning",
                        "result": result,
                        "success": True
                    })

            except Exception as e:

                print(
                    f"      ❌ {str(e)}"
                )

                results.append({
                    "step": step_number,
                    "description": description,
                    "success": False,
                    "error": str(e)
                })

        self.execution_history.extend(
            results
        )

        return results

    def _execute_tool(
        self,
        tool_name: str,
        args: Dict
    ):

        if tool_name not in self.tools_registry:

            raise ValueError(
                f"Tool '{tool_name}' not found"
            )

        tool = self.tools_registry[
            tool_name
        ]

        return tool["func"](
            **args
        )

    def _execute_reasoning(
        self,
        task: str
    ) -> str:

        prompt = f"""
You are an AI reasoning agent.

Perform the following task:

{task}

Give a concise useful result.
"""

        return self._call_gemini(prompt)

    def verify_results(
        self,
        user_goal: str,
        results: List[Dict]
    ) -> Dict:

        successful_results = [
            r for r in results
            if r.get("success") is True
        ]

        result_text = json.dumps(
            successful_results,
            indent=2,
            default=str
        )

        prompt = f"""
You are verifying the work of an AI agent.

USER GOAL:
{user_goal}

RESULTS:
{result_text}

Evaluate whether the results are sufficient.

Return ONLY valid JSON:

{{
    "completed": true,
    "score": 0.0,
    "issues": [],
    "summary": "..."
}}
"""

        response = self._call_gemini(prompt)

        try:

            return json.loads(response)

        except json.JSONDecodeError:

            return {
                "completed": len(successful_results) > 0,
                "score": 0.5,
                "issues": [],
                "summary": response
            }

    def generate_report(
        self,
        user_goal: str,
        results: List[Dict],
        verification: Dict
    ) -> str:

        result_text = json.dumps(
            results,
            indent=2,
            default=str
        )

        prompt = f"""
You are Alex.

Generate the final answer for the user.

USER GOAL:
{user_goal}

RESULTS:
{result_text}

VERIFICATION:
{json.dumps(verification, indent=2)}

Give a clear, useful answer.
Do not mention internal agent steps unless necessary.
"""

        return self._call_gemini(prompt)

    def classify_goal(
        self,
        analysis: Dict
    ) -> str:

        return analysis.get(
            "goal_type",
            "other"
        )

    def run(
        self,
        user_goal: str,
        memory_context: Optional[Dict] = None
    ) -> Dict:

        print("\n" + "=" * 50)
        print("🚀 ALEX")
        print("=" * 50)

        # 1. Understand
        print("🎯 Understanding...")

        analysis = self.understand_goal(
            user_goal
        )

        # Add memory to analysis
        if memory_context:

            analysis["memory_context"] = (
                memory_context
            )

        # 2. Planning
        print("🗺️ Planning...")

        plan = self.create_plan(
            user_goal,
            analysis
        )

        print(
            f"✅ Plan: {len(plan)} steps"
        )

        # 3. Execution
        results = self.execute_plan(
            plan
        )

        # 4. Verification
        print("\n🔍 Verifying...")

        verification = self.verify_results(
            user_goal,
            results
        )

        # 5. Final report
        print("\n📝 Generating report...")

        report = self.generate_report(
            user_goal,
            results,
            verification
        )

        return {
            "goal": user_goal,
            "analysis": analysis,
            "plan": plan,
            "results": results,
            "verification": verification,
            "report": report
        }

def search_web(
    query: str
) -> str:

    return (
        f"Web results for '{query}': "
        f"[Educational content, articles, "
        f"research papers and resources]"
    )

def research(
    topic: str = None,
    query: str = None
) -> str:

    actual_topic = topic or query

    if not actual_topic:
        actual_topic = "unknown topic"

    return (
        f"Research on {actual_topic}: "
        f"[Key insights, concepts, data and examples]"
    )

def analyze(
    text: str = None,
    focus: str = None
) -> str:

    actual_text = (
        text
        or focus
        or ""
    )

    return (
        f"Analysis: "
        f"{actual_text[:200]}..."
    )

agent = AlexAgent(
    api_key=GEMINI_API_KEY,
    model=MODEL_NAME
)

print("register_tool" in dir(agent))

agent.register_tool(
    name="search",
    func=search_web,
    description="Search for information on the web"
)

agent.register_tool(
    name="research",
    func=research,
    description="Research a topic and provide key insights"
)

agent.register_tool(
    name="analyze",
    func=analyze,
    description="Analyze text or a specific focus"
)

memory = AgentMemory()

print("🧠 Memory system initialized")

goal = "Explain what machine learning is"

print(f"\n🎯 User: {goal}")

context = memory.get_context(goal)

result = agent.run(
    goal,
    memory_context=context
)

print("\n" + "=" * 50)
print("FINAL ANSWER")
print("=" * 50)

print(result["report"])

goal = "Now explain supervised learning in simple terms"

print(f"\n🎯 User: {goal}")

context = memory.get_context(goal)

result = agent.run(
    goal,
    memory_context=context
)

print("\n" + "=" * 50)
print("FINAL ANSWER")
print("=" * 50)

print(result["report"])

goal_type = agent.classify_goal(
    result["analysis"]
)

memory.remember_goal(
    goal=goal,
    goal_type=goal_type,
    result=result["verification"]
)

memory.remember_conversation(
    user_message=goal,
    assistant_response=result["report"]
)

print("💾 Turn 2 saved to memory")

context = memory.get_context(
    "Explain machine learning again"
)

print(
    json.dumps(
        context,
        indent=2,
        ensure_ascii=False,
        default=str
    )
)

print("\n" + "=" * 50)
print("🧠 MEMORY SUMMARY")
print("=" * 50)

print(
    f"\nRecent conversations: "
    f"{len(memory.short_term.conversation_turns)}"
)

print(
    f"Long-term memories: "
    f"{len(memory.long_term.memories)}"
)

print(
    f"Goal types seen: "
    f"{len(memory.long_term.goal_patterns)}"
)

print("\nGoal patterns:")

for goal_type, count in memory.long_term.goal_patterns.items():

    print(
        f"  - {goal_type}: {count}"
    )

goal = "Give me another explanation of machine learning, but keep it simple"

context = memory.get_context(goal)

result = agent.run(
    goal,
    memory_context=context
)

print("\n" + "=" * 50)
print("FINAL ANSWER")
print("=" * 50)

print(result["report"])

goal_type = agent.classify_goal(
    result["analysis"]
)

memory.remember_goal(
    goal=goal,
    goal_type=goal_type,
    result=result["verification"]
)

memory.remember_conversation(
    user_message=goal,
    assistant_response=result["report"]
)

print("✅ Conversation saved")

goal_type = agent.classify_goal(
    result["analysis"]
)

memory.remember_goal(
    goal=goal,
    goal_type=goal_type,
    result=result["verification"]
)

memory.remember_conversation(
    user_message=goal,
    assistant_response=result["report"]
)

print("✅ Conversation saved")

