# -*- coding: utf-8 -*-
"""Phase_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hecxOqmhFRr4csnfj4IlAjMW3fRl_yZw
"""

# ==================== SETUP ====================
import subprocess
import sys

packages = [
    "google-genai",
    "requests",
    "beautifulsoup4",
    "pandas",
]

for package in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("✅ Dependencies installed\n")

import json
import re
from typing import Optional, Any, Dict, List
from dataclasses import dataclass, asdict
from datetime import datetime
import google.genai as genai
from google.genai import types

# Get API key from Colab secrets
from google.colab import userdata
GEMINI_API_KEY = userdata.get("GOOGLE_API_KEY")

@dataclass
class ToolCall:
    tool_name: str
    args: Dict[str, Any]
    result: Optional[Any] = None
    error: Optional[str] = None
    timestamp: str = None

    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now().isoformat()


@dataclass
class PlanStep:
    step_id: int
    description: str
    tool_required: Optional[str] = None
    args: Optional[Dict] = None
    status: str = "pending"
    result: Optional[Any] = None


@dataclass
class ExecutionPlan:
    goal: str
    steps: List[PlanStep]
    reasoning: str
    created_at: str = None

    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now().isoformat()


class AlexAgent:

    def __init__(
        self,
        api_key: str,
        model: str = "gemini-3.8-flash"
    ):
        self.api_key = api_key
        self.model = model

        # Modern Google GenAI SDK
        self.client = genai.Client(api_key=api_key)

        self.tools_registry = {}
        self.current_plan = None

        print("✅ Alex Agent initialized\n")

    def register_tool(self, name: str, func: callable, description: str):
        self.tools_registry[name] = {
            "func": func,
            "description": description,
            "name": name
        }
        print(f"📍 Tool registered: {name}")

    def _log(self, message: str):
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {message}")

    def _call_gemini(
    self,
    prompt: str,
    temperature: float = 0.7
) -> str:

        try:

            interaction = self.client.interactions.create(
                model=self.model,
                input=prompt,
                generation_config={
                    "thinking_level": "medium"
                }
            )

            return interaction.output_text

        except Exception as e:

            self._log(f"❌ Error: {e}")
            raise

    def understand_goal(self, user_goal: str) -> Dict:
        self._log(f"🎯 Understanding goal...")
        prompt = f"""Analyze this goal:

Goal: "{user_goal}"

Provide:
1. Clear restatement
2. Key questions
3. Information needed
4. Challenges
5. Success criteria"""

        response = self._call_gemini(prompt, temperature=0.5)
        return {
            "original_goal": user_goal,
            "analysis": response,
            "timestamp": datetime.now().isoformat()
        }

    def create_plan(self, user_goal: str, goal_analysis: Dict) -> ExecutionPlan:
        self._log(f"🗺️ Creating plan...")

        tools_desc = "\n".join([
            f"- {t['name']}: {t['description']}"
            for t in self.tools_registry.values()
        ])

        prompt = f"""Create execution plan as JSON:

Goal: "{user_goal}"

Analysis: {goal_analysis['analysis']}

Tools available:
{tools_desc}

Return JSON:
{{
    "reasoning": "...",
    "steps": [
        {{
            "step_id": 1,
            "description": "...",
            "tool_required": "name or null",
            "args": {{}} or null
        }}
    ]
}}"""

        response = self._call_gemini(prompt, temperature=0.3)

        try:
            json_match = re.search(r'\{.*\}', response, re.DOTALL)
            plan_data = json.loads(json_match.group()) if json_match else {"reasoning": "", "steps": []}
        except:
            plan_data = {"reasoning": "Plan", "steps": [{"step_id": 1, "description": user_goal}]}

        steps = [
            PlanStep(
                step_id=step.get("step_id", i),
                description=step.get("description", ""),
                tool_required=step.get("tool_required"),
                args=step.get("args")
            )
            for i, step in enumerate(plan_data.get("steps", []))
        ]

        plan = ExecutionPlan(goal=user_goal, steps=steps, reasoning=plan_data.get("reasoning", ""))
        self.current_plan = plan
        self._log(f"✅ Plan created: {len(steps)} steps")
        return plan

    def execute_plan(self, plan: ExecutionPlan) -> List[ToolCall]:
        self._log(f"⚙️ Executing plan...\n")
        results = []

        for i, step in enumerate(plan.steps, 1):
            step.status = "in_progress"
            self._log(f"  Step {i}: {step.description[:50]}...")

            try:
                if step.tool_required and step.tool_required in self.tools_registry:
                    result = self._execute_tool(step.tool_required, step.args or {})
                else:
                    result = self._execute_reasoning(step.description, results)

                step.result = result
                step.status = "completed"
                tool_call = ToolCall(
                    tool_name=step.tool_required or "reasoning",
                    args=step.args or {},
                    result=result
                )
                results.append(tool_call)
                self._log(f"    ✅ Done")
            except Exception as e:
                step.status = "failed"
                self._log(f"    ❌ Failed: {e}")
                results.append(ToolCall(
                    tool_name=step.tool_required or "reasoning",
                    args=step.args or {},
                    error=str(e)
                ))

        self._log(f"\n✅ Execution complete")
        return results

    def _execute_tool(self, tool_name: str, args: Dict) -> Any:
        tool = self.tools_registry[tool_name]
        return tool["func"](**args)

    def _execute_reasoning(self, task: str, context: List[ToolCall]) -> str:
        context_str = ""
        if context:
            context_str = "\n\nPrevious:\n"
            for call in context[-2:]:
                context_str += f"- {call.tool_name}: {str(call.result)[:150]}...\n"

        prompt = f"Task: {task}\n{context_str}\nProvide response:"
        return self._call_gemini(prompt)

    def verify_results(self, plan: ExecutionPlan, results: List[ToolCall]) -> Dict:
        self._log(f"🔍 Verifying...")

        results_summary = "\n".join([
            f"- {r.tool_name}: {str(r.result)[:200]}"
            for r in results if r.result
        ])

        prompt = f"""Verify results for goal: "{plan.goal}"

Results:
{results_summary}

Assess:
1. Goal achieved?
2. Quality of results?
3. Confidence (0-100%)?
4. Gaps or issues?"""

        verification = self._call_gemini(prompt, temperature=0.3)
        self._log("✅ Verification done")

        return {
            "report": verification,
            "total_steps": len(plan.steps),
            "completed": sum(1 for s in plan.steps if s.status == "completed")
        }

    def generate_report(self, goal: str, plan: ExecutionPlan, results: List[ToolCall], verification: Dict) -> str:
        self._log(f"📄 Generating report...")

        results_text = "\n".join([
            f"**{r.tool_name}**: {str(r.result)[:300]}"
            for r in results if r.result
        ])

        prompt = f"""Create Markdown report:

Goal: {goal}

Approach: {plan.reasoning}

Findings:
{results_text}

Assessment:
{verification['report']}

Format with:
## Executive Summary
## Methodology
## Key Findings
## Analysis
## Conclusion"""

        report = self._call_gemini(prompt)
        self._log("✅ Report ready")
        return report

    def run(self, user_goal: str) -> Dict:
        self._log(f"\n{'='*50}\n🚀 STARTING ALEX AGENT\n{'='*50}")

        goal_analysis = self.understand_goal(user_goal)
        plan = self.create_plan(user_goal, goal_analysis)
        results = self.execute_plan(plan)
        verification = self.verify_results(plan, results)
        report = self.generate_report(user_goal, plan, results, verification)

        return {
            "goal": user_goal,
            "plan_steps": len(plan.steps),
            "completed_steps": verification['completed'],
            "final_report": report
        }

# ==================== TOOLS ====================

def search_web(query: str) -> str:
    return f"Search results for '{query}': Wikipedia, news, research papers on topic"

def research(topic: str) -> str:
    return f"In-depth research on {topic}: industry trends, data, case studies"

def analyze_text(text: str) -> str:
    return f"Analysis of: Key themes, entities, sentiment, and summary"

# ==================== RUN AGENT ====================

print("\n" + "="*50)
print("ALEX AGENT — PHASE 1 TEST")
print("="*50 + "\n")

# Initialize
agent = AlexAgent(api_key=GEMINI_API_KEY)

# Register tools
agent.register_tool("search_web", search_web, "Search web. Args: query")
agent.register_tool("research", research, "Research topic. Args: topic")
agent.register_tool("analyze_text", analyze_text, "Analyze text. Args: text")

print("\n" + "="*50)
print("RUNNING FIRST TEST")
print("="*50 + "\n")

# Run with example goal
goal = "Explain what AI agents are and how they differ from chatbots"

result = agent.run(goal)

print("\n" + "="*50)
print("EXECUTION RESULTS")
print("="*50)
print(f"\n✅ Completed: {result['completed_steps']}/{result['plan_steps']} steps")
print(f"\n📄 FINAL REPORT:\n\n{result['final_report']}")

goal = "Compare machine learning and deep learning"
result = agent.run(goal)
print(result['final_report'])

