# -*- coding: utf-8 -*-
"""Phase_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZhcHvwa_bxDTFo4E6InJgkfoSYfr8f-

'''
Alex Agent — Phase 3: RAG Integration

Now with:
- Document ingestion
- Embedding generation
- Vector search
- Source citation
- Context-aware responses
'''
"""

# ==================== SETUP ====================

import subprocess
import sys

packages = ["google-genai", "requests", "beautifulsoup4", "pandas", "numpy"]
for package in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

print("✅ Dependencies installed\n")

# ==================== IMPORTS ====================

import json
import re
import hashlib
import numpy as np

from typing import Optional, Any, Dict, List, Tuple
from dataclasses import dataclass
from datetime import datetime

import google.genai as genai

# ==================== GEMINI API KEY ====================

from google.colab import userdata

GEMINI_API_KEY = userdata.get("GOOGLE_API_KEY")

if not GEMINI_API_KEY:
    raise ValueError(
        "❌ GOOGLE_API_KEY not found in Colab Secrets."
    )

print("✅ Gemini API key loaded")

# ==================== DOCUMENT MODELS ====================

@dataclass
class Document:
    id: str
    name: str
    content: str
    source: str
    metadata: Dict = None
    chunks: List = None

    def __post_init__(self):

        if self.metadata is None:
            self.metadata = {}

        if self.chunks is None:
            self.chunks = []


@dataclass
class DocumentChunk:
    id: str
    document_id: str
    content: str
    chunk_index: int
    embedding: Optional[List[float]] = None
    metadata: Dict = None

    def __post_init__(self):

        if self.metadata is None:
            self.metadata = {}


@dataclass
class RetrievalResult:
    chunk: DocumentChunk
    similarity_score: float
    document_name: str
    rank: int

# ==================== DOCUMENT PROCESSOR ====================

class DocumentProcessor:

    @staticmethod
    def chunk_text(
        text: str,
        chunk_size: int = 500,
        overlap: int = 100
    ) -> List[str]:

        sentences = re.split(
            r'(?<=[.!?])\s+',
            text.strip()
        )

        chunks = []

        current_chunk = []
        current_size = 0

        for sentence in sentences:

            sentence_len = len(sentence.split())

            if (
                current_size + sentence_len > chunk_size
                and current_chunk
            ):

                chunks.append(
                    " ".join(current_chunk)
                )

                # Approximate overlap
                overlap_count = max(
                    1,
                    overlap // 20
                )

                current_chunk = (
                    current_chunk[-overlap_count:]
                    + [sentence]
                )

                current_size = sum(
                    len(s.split())
                    for s in current_chunk
                )

            else:

                current_chunk.append(sentence)
                current_size += sentence_len

        if current_chunk:

            chunks.append(
                " ".join(current_chunk)
            )

        return chunks

# ==================== EMBEDDING GENERATOR ====================

class EmbeddingGenerator:

    def __init__(
        self,
        use_gemini: bool = False,
        api_key: Optional[str] = None
    ):

        self.use_gemini = use_gemini
        self.api_key = api_key

        self._embedding_cache = {}

        if use_gemini and api_key:

            self.client = genai.Client(
                api_key=api_key
            )

        else:

            self.client = None

    def generate_embedding(
        self,
        text: str
    ) -> List[float]:

        text_hash = hashlib.md5(
            text.encode()
        ).hexdigest()

        if text_hash in self._embedding_cache:

            return self._embedding_cache[text_hash]

        if self.use_gemini and self.client:

            try:

                response = self.client.models.embed_content(
                    model="models/embedding-001",
                    content=text
                )

                embedding = response["embedding"]

            except Exception:

                embedding = self._simple_embedding(text)

        else:

            embedding = self._simple_embedding(text)

        self._embedding_cache[text_hash] = embedding

        return embedding

    @staticmethod
    def _simple_embedding(
        text: str,
        dim: int = 384
    ) -> List[float]:

        text_hash = hashlib.md5(
            text.encode()
        ).hexdigest()

        seed = int(text_hash, 16)

        np.random.seed(
            seed % (2**31)
        )

        embedding = np.random.randn(
            dim
        ).astype(float)

        norm = np.linalg.norm(
            embedding
        )

        embedding = embedding / norm

        return embedding.tolist()

    def embed_chunks(
        self,
        chunks: List[DocumentChunk]
    ) -> List[DocumentChunk]:

        for i, chunk in enumerate(chunks):

            embedding = self.generate_embedding(
                chunk.content
            )

            chunk.embedding = embedding

            if (i + 1) % 10 == 0:

                print(
                    f"  📊 Embedded "
                    f"{i + 1}/{len(chunks)}"
                )

        return chunks

# ==================== VECTOR STORE ====================

class VectorStore:

    def __init__(self):

        self.chunks: Dict[
            str, DocumentChunk
        ] = {}

        self.documents: Dict[
            str, Document
        ] = {}

    def add_document(
        self,
        document: Document
    ):

        self.documents[
            document.id
        ] = document

        for chunk in document.chunks:

            if chunk.embedding is not None:

                self.chunks[
                    chunk.id
                ] = chunk

    def search(
        self,
        query_embedding: List[float],
        top_k: int = 5
    ) -> List[RetrievalResult]:

        if not self.chunks:
            return []

        scores = []

        query_vec = np.array(
            query_embedding
        )

        query_norm = np.linalg.norm(
            query_vec
        )

        for chunk_id, chunk in self.chunks.items():

            if chunk.embedding is None:
                continue

            chunk_vec = np.array(
                chunk.embedding
            )

            chunk_norm = np.linalg.norm(
                chunk_vec
            )

            similarity = (
                np.dot(
                    query_vec,
                    chunk_vec
                )
                /
                (
                    query_norm * chunk_norm
                    + 1e-8
                )
            )

            scores.append(
                (
                    chunk_id,
                    similarity,
                    chunk
                )
            )

        scores.sort(
            key=lambda x: x[1],
            reverse=True
        )

        results = []

        for rank, (
            chunk_id,
            similarity,
            chunk
        ) in enumerate(
            scores[:top_k],
            start=1
        ):

            doc = self.documents[
                chunk.document_id
            ]

            results.append(
                RetrievalResult(
                    chunk=chunk,
                    similarity_score=float(
                        similarity
                    ),
                    document_name=doc.name,
                    rank=rank
                )
            )

        return results

    def get_stats(self) -> Dict:

        return {
            "total_documents":
                len(self.documents),

            "total_chunks":
                len(self.chunks),

            "documents": [
                {
                    "name": doc.name,
                    "chunks": len(doc.chunks),
                    "source": doc.source
                }
                for doc in self.documents.values()
            ]
        }

# ==================== RAG RETRIEVER ====================

class RAGRetriever:

    def __init__(
        self,
        embedding_generator: EmbeddingGenerator,
        vector_store: VectorStore
    ):

        self.embeddings = embedding_generator
        self.store = vector_store

        self.retrieval_history = []

    def retrieve(
        self,
        query: str,
        top_k: int = 5
    ) -> List[RetrievalResult]:

        query_embedding = (
            self.embeddings.generate_embedding(
                query
            )
        )

        results = self.store.search(
            query_embedding,
            top_k=top_k
        )

        self.retrieval_history.append({
            "query": query,
            "results": len(results),
            "timestamp":
                datetime.now().isoformat()
        })

        return results

    def format_context(
        self,
        results: List[RetrievalResult]
    ) -> Tuple[str, List[Dict]]:

        context_parts = []
        citations = []

        for result in results:

            context_parts.append(
                f"[Source: {result.document_name}]\n"
                f"{result.chunk.content}"
            )

            citations.append({
                "source":
                    result.document_name,

                "similarity":
                    result.similarity_score,

                "rank":
                    result.rank
            })

        context = "\n\n---\n\n".join(
            context_parts
        )

        return context, citations

# ==================== RAG SYSTEM ====================

class RAGSystem:

    def __init__(
        self,
        use_gemini: bool = False,
        api_key: Optional[str] = None
    ):

        self.processor = DocumentProcessor()

        self.embeddings = EmbeddingGenerator(
            use_gemini=use_gemini,
            api_key=api_key
        )

        self.store = VectorStore()

        self.retriever = RAGRetriever(
            self.embeddings,
            self.store
        )

        print("✅ RAG System initialized")

    def ingest_text(
        self,
        text: str,
        name: str = "document",
        chunk_size: int = 500
    ):

        print(f"\n📥 Ingesting: {name}")

        doc_id = hashlib.md5(
            name.encode()
        ).hexdigest()[:8]

        document = Document(
            id=doc_id,
            name=name,
            content=text,
            source=f"text:{name}"
        )

        chunks_text = (
            self.processor.chunk_text(
                text,
                chunk_size=chunk_size
            )
        )

        for i, chunk_text in enumerate(
            chunks_text
        ):

            chunk = DocumentChunk(
                id=f"{doc_id}_chunk_{i}",
                document_id=doc_id,
                content=chunk_text,
                chunk_index=i
            )

            document.chunks.append(
                chunk
            )

        print(
            f"  ✅ {len(document.chunks)} chunks"
        )

        print(
            "  🧮 Generating embeddings..."
        )

        document.chunks = (
            self.embeddings.embed_chunks(
                document.chunks
            )
        )

        self.store.add_document(
            document
        )

        print("  ✅ Stored")

    def retrieve(
        self,
        query: str,
        top_k: int = 5
    ) -> Tuple[str, List[Dict]]:

        results = (
            self.retriever.retrieve(
                query,
                top_k=top_k
            )
        )

        context, citations = (
            self.retriever.format_context(
                results
            )
        )

        return context, citations

    def get_status(self) -> Dict:

        stats = self.store.get_stats()

        return {
            "documents":
                stats["total_documents"],

            "chunks":
                stats["total_chunks"],

            "queries":
                len(
                    self.retriever
                    .retrieval_history
                )
        }

# ==================== AGENT MODELS ====================

@dataclass
class ToolCall:

    tool_name: str
    args: Dict
    result: Optional[Any] = None
    error: Optional[str] = None


@dataclass
class PlanStep:

    step_id: int
    description: str
    tool_required: Optional[str] = None
    args: Optional[Dict] = None

    status: str = "pending"

    result: Optional[Any] = None


@dataclass
class ExecutionPlan:

    goal: str
    steps: List[PlanStep]
    reasoning: str

# ==================== ALEX AGENT ====================

class AlexAgent:

    def __init__(
        self,
        api_key: str,
        rag_system: Optional[RAGSystem] = None,
        model: str = "gemini-3.8-flash"
    ):

        self.api_key = api_key

        self.client = genai.Client(
            api_key=api_key
        )

        self.rag = rag_system

        self.model = model

        self.tools_registry = {}

        self.current_plan = None

        self.execution_history = []

        print(
            "✅ Alex Agent initialized (with RAG)"
        )

        print(
            f"🤖 Model: {self.model}"
        )

    def register_tool(
        self,
        name: str,
        func: callable,
        description: str
    ):

        self.tools_registry[name] = {
            "func": func,
            "description": description,
            "name": name
        }

        print(
            f"📍 Tool: {name}"
        )

    def _log(self, message: str):

        print(
            f"[{datetime.now().strftime('%H:%M:%S')}] "
            f"{message}"
        )

    def _call_gemini(
    self,
    prompt: str,
    temperature: float = 0.7
) -> Optional[str]:

        try:

            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt,
                config={
                    "temperature": temperature
                }
            )

            return response.text

        except Exception as e:

            error_text = str(e)

            # Handle Gemini quota errors gracefully
            if (
                "429" in error_text
                or "RESOURCE_EXHAUSTED" in error_text
                or "quota" in error_text.lower()
            ):

                self._log(
                    "⚠️ Gemini API quota exhausted."
                )

                return None

            # Other errors should still be visible
            self._log(
                f"❌ Gemini Error: {e}"
            )

            raise

# ==================== ADD RAG METHOD TO ALEX ====================

def answer_with_rag(
    self,
    query: str,
    top_k: int = 3
) -> Dict:

    self._log(
        "\n" + "=" * 50
    )

    self._log(
        "🚀 ALEX + RAG"
    )

    self._log(
        "=" * 50
    )

    if not self.rag:

        raise ValueError(
            "RAG system is not connected."
        )

    # =========================
    # RETRIEVE
    # =========================

    self._log(
        "🔎 Retrieving relevant documents..."
    )

    context, citations = (
        self.rag.retrieve(
            query,
            top_k=top_k
        )
    )

    if not context:

        return {
            "query": query,
            "answer":
                "I couldn't find relevant information "
                "in the knowledge base.",
            "citations": [],
            "retrieved_chunks": 0
        }

    self._log(
        f"📚 Retrieved "
        f"{len(citations)} chunks"
    )

    # =========================
    # PROMPT
    # =========================

    prompt = f"""
You are Alex, an AI research assistant.

Answer the user's question using ONLY
the information provided in the context.

If the answer cannot be found in the context,
say that the information is not available
in the knowledge base.

User Question:
{query}

Context:
{context}

Instructions:
- Use only the provided context.
- Do not invent facts.
- Be clear and concise.
- Mention the relevant source documents.
"""

    # =========================
    # GENERATE
    # =========================

    self._log(
        "🧠 Generating answer..."
    )

    answer = self._call_gemini(
    prompt,
    temperature=0.3
)

    if answer is None:

        return {
            "query": query,
            "answer": (
                "Gemini API quota is currently exhausted. "
                "However, the RAG retrieval pipeline worked successfully."
            ),
            "citations": citations,
            "retrieved_chunks": len(citations),
            "generation_status": "quota_exhausted"
        }

    self._log(
        "✅ Answer generated"
    )

AlexAgent.answer_with_rag = answer_with_rag
print("✅ RAG answering capability added to Alex")

# ==================== TOOLS ====================

def retrieve_from_rag(
    query: str,
    rag_system: RAGSystem
) -> str:

    context, citations = (
        rag_system.retrieve(
            query,
            top_k=3
        )
    )

    return (
        f"Retrieved information:\n"
        f"{context}\n\n"
        f"Sources: {len(citations)}"
    )


def analyze(text: str) -> str:

    return (
        f"Analysis of content "
        f"(length: {len(text)} chars)"
    )

# ==================== DEMO ====================

print(
    "\n" + "=" * 50
)

print(
    "ALEX AGENT — PHASE 3: RAG INTEGRATION"
)

print(
    "=" * 50 + "\n"
)

# No Gemini embeddings
# No additional API calls

rag = RAGSystem(
    use_gemini=False
)

# ==================== DOCUMENTS ====================

print(
    "📚 INGESTING DOCUMENTS\n"
)

doc1 = """
Machine Learning is a branch of Artificial Intelligence
that focuses on creating algorithms that can learn from
data and make predictions without being explicitly programmed.

Types of Machine Learning:

1. Supervised Learning:
Learning from labeled data.

2. Unsupervised Learning:
Finding patterns in unlabeled data.

3. Reinforcement Learning:
Learning through interaction and rewards.

Key algorithms include Decision Trees, Random Forests,
Support Vector Machines (SVM), and Neural Networks.

These algorithms power applications in image recognition,
natural language processing, and predictive analytics.
"""


doc2 = """
Deep Learning uses artificial neural networks with multiple
layers (hence "deep") to process complex patterns in data.

Key Deep Learning Architectures:

1. Convolutional Neural Networks (CNNs):
Best for image processing.

2. Recurrent Neural Networks (RNNs):
Best for sequence data.

3. Transformers:
State-of-the-art for NLP.

Deep Learning has enabled breakthrough applications
in computer vision, language translation, game playing
such as AlphaGo, and more.

It requires large amounts of data and computational power
but achieves superior performance on complex tasks.
"""


rag.ingest_text(
    doc1,
    "ML_Basics.txt"
)

rag.ingest_text(
    doc2,
    "Deep_Learning.txt"
)

# ==================== INITIALIZE ALEX ====================

print(
    "\n" + "=" * 50
)

print(
    "AGENT INITIALIZATION"
)

print(
    "=" * 50
)

agent = AlexAgent(
    api_key=GEMINI_API_KEY,
    rag_system=rag,
    model="gemini-3.8-flash"
)

agent.register_tool(
    "retrieve",
    lambda q: retrieve_from_rag(q, rag),
    "Retrieve information from documents"
)

agent.register_tool(
    "analyze",
    analyze,
    "Analyze text"
)

# ==================== RAG RETRIEVAL TEST ====================

query = "Explain the different types of machine learning"

context, citations = rag.retrieve(
    query,
    top_k=2
)

print("\n" + "=" * 60)
print("RAG RETRIEVAL TEST")
print("=" * 60)

print("\n📚 CONTEXT:\n")
print(context)

print("\n📌 CITATIONS:\n")

for citation in citations:
    print(citation)

# ==================== TEST 1 ====================

print(
    "\n📋 TEST 1"
)

query = (
    "Explain the different types "
    "of machine learning"
)

result = agent.answer_with_rag(
    query,
    top_k=2
)

print(
    "\n" + "=" * 60
)

print(
    "FINAL ANSWER"
)

print(
    "=" * 60
)

print(
    result["answer"]
)